/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alan' at '9/4/16 1:08 PM' with Gradle 2.10
 *
 * @author Alan, @date 9/4/16 1:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
